### ISSUE TITLE
No memory leak?

### ISSUE THREAD

**Issue by mishashevelinn** [mishashevelinn/BSTree#1]
After removing `delete` no memory leak detected by Valgrind's memcheck:
https://github.com/mishashevelinn/BSTree/blob/42c2531329bc2acd60e209d7cce2fd8df06edbde/BST.h#L92-L94
Also allocating new Tree object and array of integers in `main` with no deletion followed:
https://github.com/mishashevelinn/BSTree/blob/73ca4c01b234e69286300357cefc6b4a7cfd2874/main.cpp#L5
https://github.com/mishashevelinn/BSTree/blob/73ca4c01b234e69286300357cefc6b4a7cfd2874/main.cpp#L8-L10

Valgrind out:
![image](https://user-images.githubusercontent.com/59566253/103708391-2dbf7c00-4fb9-11eb-8e0c-41fd5a49d9a5.png)

Why?

**Comment by mishashevelinn** [comment]
@shma2001gmailcom

**Comment by mishashevelinn** [comment]
@Abziz 
Valgrind קיבל ארגומנט לא נכון
במקום ./test
התקבל test   
יצאתי סטלן
XD

**Comment by shma2001gmailcom** [comment]
Tree<int> * t = new Tree<int>(); is controlled by Tree destructor while Tree instance is used as local variable.
